services:
    gbprod.elasticsearch_dataprovider.registry:
        class: GBProd\ElasticsearchDataProviderBundle\DataProvider\Registry
        
    gbprod.elasticsearch_dataprovider.handler:
        class: GBProd\ElasticsearchDataProviderBundle\DataProvider\Handler
        arguments:
            - '@gbprod.elasticsearch_dataprovider.registry'